/**SUBMISSION CONSTANTS */
export const GET_ALL_SUBMISSIONS = "GET_ALL_SUBMISSIONS";
export const ADD_SUBMISSION = "ADD_SUBMISSION";

/**WORKSHOPS CONSTANTS */
export const GET_ALL_WORKSHOPS = "GET_ALL_WORKSHOPS";
export const ADD_WORKSHOP = "ADD_WORKSHOP";

/**CONFERENCE CONSTANTS */
export const ADD_CONFERENCE = "ADD_CONFERENCE";
export const GET_ALL_CONFERENCE = "GET_ALL_CONFERENCE";
export const EDIT_CONFERENCE = "EDIT_CONFERENCE";

/**DOCUMENT CONSTANTS */
export const ADD_DOCUMENTS = "ADD_DOCUMENTS";
export const RESEARCH = "RESEARCH";
export const W_PROPOSAL = "W_PROPOSAL";
export const PENDING = "PENDING"

export const ADMIN = "ADMIN"
export const TEMPLATE = "TEMPLATE"
